# In case the platform does NOT support this type of sensors
ccflags-y += -I$(srctree)/drivers/misc/mediatek/hwmon/include
obj-y   +=  captouch.o

obj-$(CONFIG_MTK_IQS128)	+=  iqs128/
obj-$(CONFIG_MTK_IQS263)	+=  iqs263/
